[Definition]
failregex = ^.*"remote_addr":"<HOST>".*"uri":"/.*\.php.*","status":404.*$
            ^.*"remote_addr":"<HOST>".*"uri":"/wp-admin.*","status":404.*$
            ^.*"remote_addr":"<HOST>".*"uri":"/wp-content.*","status":404.*$
            ^.*"remote_addr":"<HOST>".*"uri":"/wp-includes.*","status":404.*$
            ^.*"remote_addr":"<HOST>".*"uri":"/xmlrpc\.php.*","status":404.*$

ignoreregex =