server {
    listen 80;

    location / {
        return 200 "nginx is running\n";
    }

    location /security-center/ {
        alias /usr/share/nginx/html/security-center/;
        index index.html;
    }

    location /stub_status {
        stub_status;
        allow 127.0.0.1;
        allow 172.16.0.0/12;
        deny all;
    }
}
